import React,{useEffect,useMemo,useState} from 'react';
import {adminCreate,adminDelete,adminList,adminLogin,adminLogout,adminUpdate,adminVisits,isAdminLoggedIn} from '../lib/adminApi';
import {Document,Packer,Paragraph,Table as DocxTable,TableCell,TableRow,TextRun} from 'docx';
import * as XLSX from 'xlsx'; import {jsPDF} from 'jspdf'; import './AdminPage.css';
const forms={blog:{slug:'',title:'',content:'',sort_order:0},project:{title:'',slug:'',category:'',video_src:'',is_external_link:false,has_blob:false,show_carousel:true,is_vertical:false,description:'',sort_order:0},writing:{external_id:'',title:'',url:'',sort_order:0}};
const cols={blog:['id','slug','title','content','sort_order','created_at','updated_at'],project:['id','title','slug','category','video_src','is_external_link','has_blob','show_carousel','is_vertical','description','sort_order','created_at','updated_at'],writing:['id','external_id','title','url','sort_order','created_at','updated_at'],visits:['id','username','email','os','browser','ip_address','location','macaddress','path','referrer','visited_at']};
const names={blog:'Blogs',project:'Projects',writing:'Writings',visits:'Visits'}; const pretty=k=>k.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function AdminPage(){
 const[logged,setLogged]=useState(isAdminLoggedIn()),[email,setEmail]=useState('admin@anish.com'),[password,setPassword]=useState(''),[err,setErr]=useState(''),[active,setActive]=useState('blog'),[rows,setRows]=useState([]),[q,setQ]=useState(''),[limit,setLimit]=useState(10),[pg,setPg]=useState(1),[edit,setEdit]=useState(null),[form,setForm]=useState(forms.blog),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 const crud=active!=='visits';
 const load=async()=>{setLoading(true);try{const d=active==='visits'?await adminVisits():await adminList(active);setRows(d.rows||[]);setPg(1)}catch(e){if(/Unauthorized/i.test(e.message)){setLogged(false);localStorage.removeItem('anish_admin_token')}setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{if(logged)load()},[logged,active]);
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return x?rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(x))):rows},[rows,q]);
 const shown=filtered.slice((pg-1)*limit,pg*limit), pages=Math.max(1,Math.ceil(filtered.length/limit));
 const login=async e=>{e.preventDefault();setErr('');try{await adminLogin(email,password);setLogged(true);setPassword('')}catch(e){setErr(e.message)}};
 const reset=()=>{setEdit(null);setForm({...forms[active]})};
 const editRow=r=>{const f={...forms[active]};Object.keys(f).forEach(k=>f[k]=r[k]??f[k]);setEdit(r.id);setForm(f);window.scrollTo({top:0,behavior:'smooth'})};
 const save=async e=>{e.preventDefault();setLoading(true);try{edit?await adminUpdate(active,edit,form):await adminCreate(active,form);setMsg(edit?'Updated successfully.':'Added successfully.');reset();await load()}catch(e){setMsg(e.message)}finally{setLoading(false)}};
 const del=async id=>{if(!confirm('Delete this item?'))return;try{await adminDelete(active,id);setMsg('Deleted successfully.');await load()}catch(e){setMsg(e.message)}};
 const exportData=filtered,name=`${active}-report`;
 const copy=async()=>{const c=cols[active];await navigator.clipboard.writeText([c.join('\t'),...exportData.map(r=>c.map(k=>String(r[k]??'')).join('\t'))].join('\n'));setMsg('Filtered report copied.')};
 const excel=()=>{const c=cols[active],d=exportData.map(r=>Object.fromEntries(c.map(k=>[pretty(k),r[k]??'']))),ws=XLSX.utils.json_to_sheet(d),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,names[active]);XLSX.writeFile(wb,name+'.xlsx')};
 const docx=async()=>{const c=cols[active],head=new TableRow({children:c.map(k=>new TableCell({children:[new Paragraph({children:[new TextRun({text:pretty(k),bold:true})]})]}))}),body=exportData.map(r=>new TableRow({children:c.map(k=>new TableCell({children:[new Paragraph(String(r[k]??''))]}))})),d=new Document({sections:[{children:[new Paragraph({text:names[active]+' Report',heading:'Heading1'}),new DocxTable({rows:[head,...body]})]}]});download(await Packer.toBlob(d),name+'.docx')};
 const pdf=()=>{const c=cols[active],d=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'}),m=24,w=(d.internal.pageSize.getWidth()-48)/c.length;let y=40;d.setFontSize(14);d.text(names[active]+' Report',m,y);y+=22;d.setFontSize(7);const row=a=>{if(y>d.internal.pageSize.getHeight()-25){d.addPage();y=30}a.forEach((v,i)=>d.text(String(v??'').slice(0,30),m+i*w,y,{maxWidth:w-3}));y+=12};row(c.map(pretty));exportData.forEach(r=>row(c.map(k=>r[k])));d.save(name+'.pdf')};
 if(!logged)return <div className="admin-login-page"><form className="admin-login-card" onSubmit={login}><div className="admin-kicker">ANISH PORTFOLIO</div><h1>Admin Login</h1><p>Manage portfolio content and visit activity.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{err&&<div className="admin-error">{err}</div>}<button className="admin-primary">Login</button></form></div>;
 return <div className="admin-shell"><header className="admin-topbar"><div><div className="admin-kicker">ANISH PORTFOLIO</div><h1>Admin Panel</h1></div><button onClick={async()=>{await adminLogout();setLogged(false)}}>Logout</button></header>
 <nav className="admin-tabs">{Object.keys(names).map(k=><button className={active===k?'active':''} key={k} onClick={()=>{setActive(k);setQ('');setEdit(null)}}>{names[k]}</button>)}</nav><main className="admin-main">
 {crud&&<form className="admin-form" onSubmit={save}><div className="admin-form-head"><h2>{edit?'Edit ':'Add '}{names[active].slice(0,-1)}</h2><button type="button" onClick={reset}>Clear</button></div><div className="admin-grid">{Object.keys(form).map(k=>{const b=typeof form[k]==='boolean',a=k==='content'||k==='description';return <label key={k}>{pretty(k)}{b?<span className="check-field"><input type="checkbox" checked={form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/>{form[k]?'Yes':'No'}</span>:a?<textarea rows="5" value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>})}</div><button className="admin-primary" disabled={loading}>{edit?'Update':'Add'}</button></form>}
 <section className="admin-report"><div className="admin-report-head"><div><h2>{names[active]} Report</h2><span>{filtered.length} records</span></div><div className="admin-tools"><input className="admin-search" placeholder="Search..." value={q} onChange={e=>{setQ(e.target.value);setPg(1)}}/><select value={limit} onChange={e=>{setLimit(+e.target.value);setPg(1)}}><option>10</option><option>20</option><option>50</option><option>100</option></select><button onClick={copy}>Copy</button><button onClick={excel}>Excel</button><button onClick={docx}>DOCX</button><button onClick={pdf}>PDF</button></div></div>{msg&&<div className="admin-message">{msg}</div>}<div className="admin-table-wrap">{loading?<div className="admin-empty">Loading...</div>:<table><thead><tr>{cols[active].map(k=><th key={k}>{pretty(k)}</th>)}{crud&&<th>Actions</th>}</tr></thead><tbody>{shown.length?shown.map(r=><tr key={r.id}>{cols[active].map(k=><td key={k} title={String(r[k]??'')}>{String(r[k]??'')}</td>)}{crud&&<td className="admin-actions"><button onClick={()=>editRow(r)}>Edit</button><button className="danger" onClick={()=>del(r.id)}>Delete</button></td>}</tr>):<tr><td colSpan={cols[active].length+(crud?1:0)}><div className="admin-empty">No records found.</div></td></tr>}</tbody></table>}</div><div className="admin-pagination"><button disabled={pg<=1} onClick={()=>setPg(pg-1)}>Previous</button><span>Page {pg} of {pages}</span><button disabled={pg>=pages} onClick={()=>setPg(pg+1)}>Next</button></div></section></main></div>
}